using Emart_DotNet.Models;
// Models namespace
// Contains database entity models (Address, Customer, Order, etc.)
// Address model maps to database Address table

using System.Collections.Generic;
// System.Collections.Generic namespace
// Provides List<T>, Dictionary<T,K>, ICollection<T>, etc.
// Used here for List<Address> return type

using System.Threading.Tasks;
// System.Threading.Tasks namespace
// Provides Task and Task<T> for asynchronous operations
// Allows non-blocking database calls

namespace Emart_DotNet.Services
// Services namespace - groups all business logic interfaces and implementations
// Service layer = between controller and repository
// Handles validation, business rules, orchestration of data operations
{
    public interface IAddressService
    // Interface = contract defining what methods MUST be implemented
    // IAddressService = defines address-related business operations
    // "I" prefix = naming convention for interfaces (C# standard)
    // Why use interface?
    // 1. Dependency Inversion Principle - depend on abstraction, not concrete class
    // 2. Loose coupling - controller depends on IAddressService, not AddressService
    // 3. Easy testing - can mock IAddressService with fake implementation
    // 4. Multiple implementations - can have AddressService, MockAddressService, CachedAddressService, etc.
    // 5. Extensibility - add new implementations without changing existing code
    // 
    // Example: AddressController depends on IAddressService
    // If we need to add caching: create CachedAddressService(IAddressService inner)
    // No need to change controller - still depends on IAddressService
    {
        Task<Address> AddAddressAsync(int userId, Address address);
        // Purpose: Add/Save new address for a user
        // 
        // Parameters:
        // - int userId: Which customer/user is adding this address
        //   Used to link address to correct user in database
        //   Example: userId = 5 → address belongs to customer with id 5
        //
        // - Address address: Address object containing details
        //   Properties: City, Country, State, Pincode, HouseNumber, Landmark, Town
        //   This comes from controller (user input)
        //   Will be saved to database Address table
        //
        // Return: Task<Address>
        // - Task = asynchronous operation (returns immediately, completes later)
        // - <Address> = when task completes, returns Address object
        // - Returned address includes AddressId (auto-generated by DB)
        // - Useful for client: to know which address was created (id = 5)
        //
        // Business Logic Handled Here:
        // - Validation: pincode format, state exists, country valid?
        // - Database Insert: save to Address table
        // - Relationship: link to user via UserId FK
        // - Error handling: duplicate check, DB errors, validation errors
        // - Logging: log address creation for audit trail
        //
        // Example Flow:
        // 1. Controller receives POST /api/addresses with userId=5, address data
        // 2. Controller calls await _addressService.AddAddressAsync(5, address)
        // 3. Service validates: pincode format, state, country
        // 4. Service saves to database: INSERT INTO Address (City, State, UserId...) VALUES (...)
        // 5. Database returns address with auto-generated AddressId = 10
        // 6. Service returns Address(Id=10, City="Pune", UserId=5, ...)
        // 7. Controller returns to client: HTTP 200 with address data
        //
        // Why async?
        // - Database calls are I/O operations (slow)
        // - async/await = don't block thread while waiting for DB
        // - One thread can handle multiple requests = better scalability
        // - If sync: thread blocks → wastes thread pool resource
        // - If async: thread released → can handle other requests
        //
        // Why return Address?
        // - Client needs to know created address details and ID
        // - Confirmation: "address saved with ID 10"
        // - Frontend stores this ID for future updates/deletes

        Task<List<Address>> GetAddressesByCustomerAsync(int userId);
        // Purpose: Fetch all addresses for a specific customer/user
        //
        // Parameters:
        // - int userId: Which customer's addresses to retrieve
        //   Example: userId = 5 → get all addresses where UserId = 5
        //
        // Return: Task<List<Address>>
        // - Task = asynchronous operation
        // - <List<Address>> = when task completes, returns list of addresses
        // - List might be empty if user has no addresses yet
        // - Each Address in list has all properties: City, State, Pincode, etc.
        //
        // Business Logic Handled Here:
        // - Database Query: SELECT * FROM Address WHERE UserId = @userId
        // - Filtering: only return addresses belonging to this user (security)
        // - Include navigation properties? (Orders, Customers linked to address?)
        // - Sorting: by creation date? by address type?
        // - Error handling: invalid userId, DB errors
        // - Authorization: verify requesting user has permission (not accessing other user's addresses)
        //
        // Example Flow:
        // 1. Controller receives GET /api/addresses?userId=5
        // 2. Controller calls await _addressService.GetAddressesByCustomerAsync(5)
        // 3. Service queries: SELECT * FROM Address WHERE UserId = 5
        // 4. Database returns: [Address(Id=1, City="Pune"), Address(Id=2, City="Mumbai")]
        // 5. Service returns List with 2 addresses
        // 6. Controller converts to DTO and returns JSON list to client
        //
        // Why List<Address>?
        // - One user can have multiple addresses (home, office, relative's place)
        // - Need to show all addresses in frontend dropdown
        // - User selects which address to use for delivery
        // - Returning List (not ICollection) = immutable from client perspective
        //
        // Security Consideration:
        // - MUST filter by userId to prevent SQL injection attacks
        // - Don't allow: GetAddressesByCustomerAsync(-1) to get all addresses
        // - Validate userId > 0
        // - Verify requesting user has permission to view this userId's addresses
        //
        // Why async?
        // - Database query might take time (large result set)
        // - async/await = non-blocking, scalable
        // - Multiple users can fetch their addresses simultaneously

        Task DeleteAddressAsync(int addressId);
        // Purpose: Delete a specific address
        //
        // Parameters:
        // - int addressId: Which address to delete
        //   Example: addressId = 10 → delete from Address table where AddressId = 10
        //
        // Return: Task (no generic type)
        // - Task = asynchronous operation
        // - No <T> = returns void (no value returned)
        // - Task completes when delete is done
        // - If exception thrown: delete failed (caught by controller)
        //
        // Business Logic Handled Here:
        // - Authorization: verify user can delete this address (not deleting other user's address)
        // - Validation: check address exists before deleting
        // - Foreign Key Check: can we delete? (are there orders using this address?)
        //   Option 1: Don't allow delete if orders exist
        //   Option 2: Soft delete (mark as deleted, don't remove from DB)
        //   Option 3: Cascade delete (delete orders too)
        //   Business decides which approach
        // - Database Delete: DELETE FROM Address WHERE AddressId = @addressId
        // - Error handling: address not found, foreign key constraint, DB errors
        // - Logging: log deletion for audit trail
        //
        // Example Flow:
        // 1. Controller receives DELETE /api/addresses/10
        // 2. Controller calls await _addressService.DeleteAddressAsync(10)
        // 3. Service validates: address exists, user has permission, no foreign key issues
        // 4. Service executes: DELETE FROM Address WHERE AddressId = 10
        // 5. Database removes the record
        // 6. Service returns (no value, just confirms completion)
        // 7. Controller returns HTTP 200 or 204 (success)
        //
        // Why Task (not Task<bool>)?
        // - Delete is simple: either succeeds or throws exception
        // - If success: return Task (no value needed)
        // - If fails: throw exception → caught by controller
        // - Don't need boolean "success = true/false"
        //
        // Exception-Based Error Handling:
        // - If address not found: throw new NotFoundException("Address not found")
        // - If foreign key constraint: throw new InvalidOperationException("Cannot delete address with existing orders")
        // - If DB error: throw database exception
        // - Controller catches these and returns HTTP 404, 400, 500 etc.
        //
        // Why async?
        // - Database delete operation is I/O (potentially slow)
        // - async/await = non-blocking
        // - Multiple users can delete simultaneously without blocking threads
    }
}
// End of IAddressService interface